// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeybmsgxfoutbgnkxaer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpleWJtc2d4Zm91dGJnbmt4YWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjA2MjMsImV4cCI6MjA2MzAzNjYyM30.UVxO0T55MoMMg7SVzGrcnG3se5tySFnkNZuyhvdaQ3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);